/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-DLC
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_DLC_API_H
#define INCLUDED_DLC_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_DLC_EXPORTS
#define DLC_API __GR_ATTR_EXPORT
#else
#define DLC_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_DLC_API_H */
