/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(addFlags.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8f239606ef1e4f7f5e23039156537109)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/DLC/addFlags.h>
// pydoc.h is automatically generated in the build directory
#include <addFlags_pydoc.h>

void bind_addFlags(py::module& m)
{

    using addFlags    = gr::DLC::addFlags;


    py::class_<addFlags, gr::block, gr::basic_block,
        std::shared_ptr<addFlags>>(m, "addFlags", D(addFlags))

        .def(py::init(&addFlags::make),
           D(addFlags,make)
        )
        



        ;




}








