/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(CRCGen.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7666259b457544dcb807bd50fb7f3f8f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/DLC/CRCGen.h>
// pydoc.h is automatically generated in the build directory
#include <CRCGen_pydoc.h>

void bind_CRCGen(py::module& m)
{

    using CRCGen    = gr::DLC::CRCGen;


    py::class_<CRCGen, gr::block, gr::basic_block,
        std::shared_ptr<CRCGen>>(m, "CRCGen", D(CRCGen))

        .def(py::init(&CRCGen::make),
           D(CRCGen,make)
        )
        



        ;




}








