/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(transport_layer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(315582967069bd452d31ca952eb1895d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/transport/transport_layer.h>
// pydoc.h is automatically generated in the build directory
#include <transport_layer_pydoc.h>

void bind_transport_layer(py::module& m)
{

    using transport_layer    = gr::transport::transport_layer;


    py::class_<transport_layer, gr::block, gr::basic_block,
        std::shared_ptr<transport_layer>>(m, "transport_layer", D(transport_layer))

        .def(py::init(&transport_layer::make),
           D(transport_layer,make)
        )
        



        ;




}








